# Generated by Django 3.2.4 on 2021-06-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteSellingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='lesson',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Lesson_carousol_image', verbose_name='lesson pdf Image'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='image3',
            field=models.ImageField(blank=True, upload_to='Lesson_carousol_image', verbose_name='lesson pdf Image'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_video_files', verbose_name='lesson_Video'),
        ),
    ]
