# Generated by Django 3.2.4 on 2021-06-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteSellingApp', '0002_auto_20210610_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='institute',
        ),
        migrations.AddField(
            model_name='course',
            name='institute',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Lesson_carousol_image', verbose_name='lesson pdf Image1'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Lesson_carousol_image', verbose_name='lesson pdf Image2'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image3',
            field=models.ImageField(blank=True, upload_to='Lesson_carousol_image', verbose_name='lesson pdf Image3'),
        ),
    ]
