# Generated by Django 3.2.4 on 2021-06-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteSellingApp', '0005_rename_note_name_review_lesson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='code',
            field=models.IntegerField(default='2901', editable=False),
        ),
    ]
