# Generated by Django 3.2.4 on 2021-06-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteSellingApp', '0011_remove_codetable_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codetable',
            name='lesson_name',
        ),
        migrations.AlterField(
            model_name='codetable',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
