# Generated by Django 3.2.4 on 2021-06-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteSellingApp', '0012_auto_20210614_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetable',
            name='lesson',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
