# Generated by Django 3.2.4 on 2021-06-08 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('university', models.CharField(blank=True, max_length=70)),
                ('subject', models.CharField(blank=True, max_length=70)),
                ('expertise', models.CharField(blank=True, max_length=70)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/user_profile_pictures', verbose_name='Profile Picture')),
                ('user_type', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], default='student', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
