# Generated by Django 3.2.4 on 2021-06-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='facebooklink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='instalink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='linkedlink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='websitelink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
