# Generated by Django 3.2.4 on 2021-06-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0005_auto_20210621_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
