# Generated by Django 3.2.4 on 2021-06-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0009_follow_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='following',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
