# Generated by Django 3.2.4 on 2021-06-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteSellingApp', '0013_codetable_lesson'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('blogApp', '0007_post_youtube_link'),
        ('appusers', '0012_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
