# Generated by Django 3.2.4 on 2021-06-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20210609_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, upload_to='topic_background_image', verbose_name='Topic Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='article',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
