# Generated by Django 3.2.4 on 2021-06-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
